/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.event.ActionEvent;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author g0056957
 */
public class appFCRView extends javax.swing.JFrame {
    
    public appFCRView() throws Exception {
        initComponents();
        JOptionPane.showMessageDialog(null, "Este programa não informa seu FCR concreto e consolidado ! Ele fornece apenas uma estimativa, com margens de erros, de acordo com seu preenchimento !");
        icon(); 
    }
    
    

    
    public void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconFCRCalc.png")));
    }
     
    public class Chamada{
        private String instancia;
        private String skill;
        private String rechamada;
        
        public Chamada(String instancia, String skill, String rechamada){
            this.instancia = instancia;
            this.skill = skill;
            this.rechamada = rechamada;
        }
    
    }
    
    ArrayList<Chamada>listaDeChamadas = new ArrayList<>();
    
    public void addChamada(){
        lblMenssagem.setText("");
        DefaultTableModel model = (DefaultTableModel) tblFCR.getModel();
        if(txtInst.getText().trim().equals("")){
            lblMenssagem.setForeground  (java.awt.Color.red);
            lblMenssagem.setText("O campo 'instância' não foi preenchido !");
            lblMenssagem.setVisible(true);  
        }else{
            Chamada chamada = new Chamada(txtInst.getText(),cbxSkl.getSelectedItem().toString(),cbxRech.getSelectedItem().toString());
            listaDeChamadas.add(chamada);
            model.addRow(new Object[] {tblFCR.getRowCount()+1,txtInst.getText(),cbxSkl.getSelectedItem().toString(),cbxRech.getSelectedItem().toString()});  
        }
        
    }
    
    public void apagaChamada()throws ArrayIndexOutOfBoundsException {
        
        try {
            DefaultTableModel model = (DefaultTableModel) tblFCR.getModel();
            model.removeRow(tblFCR.getSelectedRow());
            listaDeChamadas.remove(tblFCR.getSelectedRow());
        } catch (Exception e) {

        }
    }
    
    public void geraResultado() throws StringIndexOutOfBoundsException{
        lblMenssagem.setText("");
        Double totRechamadas = 0d;
        for (int i = 0; i < tblFCR.getRowCount(); i++) {
            if(tblFCR.getValueAt(i, 3).equals("SIM")){
                totRechamadas++;
            }
        }
           Double totFCR = (100 - ((totRechamadas*100)/tblFCR.getRowCount()));
           lblResultado.setForeground  (java.awt.Color.blue);
          try {
            lblResultado.setText("FCR total: "+totFCR.toString().substring(0, 5)+"%");
        } catch (Exception e) {
           lblResultado.setText("FCR total: "+totFCR.toString()+"%");
        }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        lblInst = new javax.swing.JLabel();
        lblSkl = new javax.swing.JLabel();
        lblRech = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFCR = new javax.swing.JTable();
        txtInst = new javax.swing.JTextField();
        cbxSkl = new javax.swing.JComboBox<>();
        cbxRech = new javax.swing.JComboBox<>();
        lblMenssagem = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuItemSobre = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenuItem2.setText("jMenuItem2");

        setTitle("Calc FCR 1.0.0");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                tray(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                pkmp(evt);
            }
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("Calc FCR");

        lblInst.setText("Instância");

        lblSkl.setText("SKILL");

        lblRech.setText("Rechamou ?");

        btnInsert.setText("Inserir");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete.setText("Apagar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblFCR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Indíce", "Instância", "SKILL", "Rechamou"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFCR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblFCRKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblFCR);
        if (tblFCR.getColumnModel().getColumnCount() > 0) {
            tblFCR.getColumnModel().getColumn(0).setResizable(false);
            tblFCR.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        txtInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstActionPerformed(evt);
            }
        });

        cbxSkl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVIA", "GPON", "IMS/SIP", "MANOBRA", "TV HIBRIDA" }));

        cbxRech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO", "SIM" }));

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        menu.setText("Menu");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Minimizar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem3);

        MenuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemSobre.setText("Sobre...");
        MenuItemSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItemSobreMouseClicked(evt);
            }
        });
        MenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSobreActionPerformed(evt);
            }
        });
        menu.add(MenuItemSobre);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnInsert)
                                .addGap(31, 31, 31)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInst)
                                    .addComponent(lblSkl))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxSkl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInst, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblRech)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxRech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerar)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenssagem, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInst)
                    .addComponent(txtInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSkl)
                    .addComponent(cbxSkl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRech)
                    .addComponent(cbxRech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMenssagem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGerar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSobreActionPerformed
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuItemSobreActionPerformed

    private void txtInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        addChamada();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        apagaChamada();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        geraResultado();
    }//GEN-LAST:event_btnGerarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void tblFCRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblFCRKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            apagaChamada();
        }
    }//GEN-LAST:event_tblFCRKeyPressed

    private void MenuItemSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItemSobreMouseClicked

    }//GEN-LAST:event_MenuItemSobreMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void tray(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_tray
                try {
            trayOpen();
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_tray

    private void pkmp(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_pkmp
        try {
            trayOpen();
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_pkmp
        
    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged

    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        try {
            trayOpen();
            evt.getWindow().setVisible(false);
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_formWindowIconified

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified
        evt.getWindow().setVisible(true);
        try {
            trayClose();
        } catch (Exception ex) {
            Logger.getLogger(appFCRView.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_formWindowDeiconified

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        try {
            trayClose();
        } catch (Exception ex) {
            Logger.getLogger(appFCRView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formMousePressed

    
    public void trayClose()throws Exception{
        SystemTray tray = SystemTray.getSystemTray();
        TrayIcon[] icon = tray.getTrayIcons();
        tray.remove(icon[0]);
       }
    
    
    /**
     *
     */
    public void trayOpen (){ 
         if (!SystemTray.isSupported()) {
            System.out.println("SystemTray is not supported");
            return;
        }

        SystemTray tray = SystemTray.getSystemTray();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image = toolkit.getImage(getClass().getResource("IconFCRCalc.png"));
    
        MouseListener mouseListener = new MouseListener() {
                public void mouseClicked(MouseEvent e) {
                    
                }
                public void mouseEntered(MouseEvent e) {
                    System.out.println("Tray Icon - Mouse entered!");                 
                }
                public void mouseExited(MouseEvent e) {
                    System.out.println("Tray Icon - Mouse exited!");                 
                }
                public void mousePressed(MouseEvent e) {
  
                }
                public void mouseReleased(MouseEvent e) {
                    System.out.println("Tray Icon - Mouse released!");                 
                }
            };
        
        
        PopupMenu menu = new PopupMenu();
        MenuItem messageItem = new MenuItem("Teste");
        messageItem.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        }
             @Override
             public void actionPerformed(java.awt.event.ActionEvent ae) {
                 JOptionPane.showMessageDialog(null, "TESTANTE !");  
             }
        });
        
        menu.add(messageItem);
        
        MenuItem closeItem = new MenuItem("Sair");
        closeItem.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        }
             @Override
             public void actionPerformed(java.awt.event.ActionEvent ae) {
                 System.exit(0); 
             }
        });
        menu.add(closeItem);
        TrayIcon icon = new TrayIcon(image, "Calc FCR 1.0.0", menu);
        icon.setImageAutoSize(true);
        icon.addMouseListener(mouseListener);

        try {
            tray.add(icon);
            
        } catch (AWTException e) {
            
        }
        
 
    }   
        
        
    public void restauraFrame(){
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appFCRView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appFCRView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appFCRView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appFCRView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new appFCRView().setVisible(true);
                } catch (Exception e) {
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemSobre;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnInsert;
    private javax.swing.JComboBox<String> cbxRech;
    private javax.swing.JComboBox<String> cbxSkl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblInst;
    private javax.swing.JLabel lblMenssagem;
    private javax.swing.JLabel lblRech;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSkl;
    private javax.swing.JMenu menu;
    private javax.swing.JTable tblFCR;
    private javax.swing.JTextField txtInst;
    // End of variables declaration//GEN-END:variables
}
