/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author g0056957
 */
public class View extends javax.swing.JPanel {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        pnlInfoChamada = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        qwerwer = new javax.swing.JTextField();
        qwerw = new javax.swing.JLabel();
        tryert = new javax.swing.JLabel();
        qwerwe = new javax.swing.JLabel();
        gdfs = new javax.swing.JComboBox<>();
        he56 = new javax.swing.JButton();
        ukuy8 = new javax.swing.JButton();
        uyjtj = new javax.swing.JComboBox<>();
        pnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        umurk = new javax.swing.JTable();
        txtMenssagem = new javax.swing.JLabel();
        ynt = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        lblTitulo.setText("FCR CALC");

        qwerwer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qwerwerActionPerformed(evt);
            }
        });

        qwerw.setText("Instância");

        tryert.setText("SKILL");

        qwerwe.setText("Rechamou?");

        gdfs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVIA", "IMS/SIP", "GPON", "MANOBRA", "TV HIBRIDA" }));
        gdfs.setAutoscrolls(true);
        gdfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdfsActionPerformed(evt);
            }
        });

        he56.setText("Inserir");
        he56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                he56ActionPerformed(evt);
            }
        });

        ukuy8.setText("Apagar");
        ukuy8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukuy8ActionPerformed(evt);
            }
        });

        uyjtj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO" }));
        uyjtj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyjtjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoChamadaLayout = new javax.swing.GroupLayout(pnlInfoChamada);
        pnlInfoChamada.setLayout(pnlInfoChamadaLayout);
        pnlInfoChamadaLayout.setHorizontalGroup(
            pnlInfoChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoChamadaLayout.createSequentialGroup()
                .addGroup(pnlInfoChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoChamadaLayout.createSequentialGroup()
                        .addGroup(pnlInfoChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tryert)
                            .addComponent(qwerw))
                        .addGap(35, 35, 35)
                        .addGroup(pnlInfoChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qwerwer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gdfs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInfoChamadaLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(pnlInfoChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qwerwe)
                    .addComponent(uyjtj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pnlInfoChamadaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(he56)
                .addGap(32, 32, 32)
                .addComponent(ukuy8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoChamadaLayout.setVerticalGroup(
            pnlInfoChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoChamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(pnlInfoChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qwerw)
                    .addComponent(qwerwer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qwerwe))
                .addGap(22, 22, 22)
                .addGroup(pnlInfoChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tryert)
                    .addComponent(gdfs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uyjtj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlInfoChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(he56)
                    .addComponent(ukuy8))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );

        umurk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Instância", "SKILL", "Rechamou?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(umurk);

        txtMenssagem.setForeground(new java.awt.Color(255, 0, 0));

        ynt.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlInfoChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtMenssagem, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ynt)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfoChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMenssagem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ynt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uyjtjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyjtjActionPerformed

    }//GEN-LAST:event_uyjtjActionPerformed

    private void ukuy8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukuy8ActionPerformed
        DefaultTableModel model = (DefaultTableModel) umurk.getModel();
        model.removeRow(umurk.getSelectedRow());
    }//GEN-LAST:event_ukuy8ActionPerformed

    private void he56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_he56ActionPerformed
        DefaultTableModel model = (DefaultTableModel) umurk.getModel();
        txtMenssagem.setVisible(false);
        txtMenssagem.setText("Favor preencher o campo Instância");
        if(qwerwer.getText().trim().equals("")){
            
            txtMenssagem.setVisible(true);
        }else{
            model.addRow(new Object [] {qwerwer.getText(),gdfs.getSelectedItem().toString(),uyjtj.getSelectedItem().toString()});
        }

    }//GEN-LAST:event_he56ActionPerformed

    private void gdfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gdfsActionPerformed

    private void qwerwerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qwerwerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qwerwerActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> gdfs;
    private javax.swing.JButton he56;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlInfoChamada;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JLabel qwerw;
    private javax.swing.JLabel qwerwe;
    private javax.swing.JTextField qwerwer;
    private javax.swing.JLabel tryert;
    private javax.swing.JLabel txtMenssagem;
    private javax.swing.JButton ukuy8;
    private javax.swing.JTable umurk;
    private javax.swing.JComboBox<String> uyjtj;
    private javax.swing.JButton ynt;
    // End of variables declaration//GEN-END:variables
}
